// TrendOS Attendance Clock-in V1
// Records the original daily clock-in against the scheduled Cairo start time.
const ATT_CLOCKIN_TZ_V1='Africa/Cairo';
const ATT_CLOCKIN_SPECIAL_SHEET_V1='تشغيل - مواعيد خاصة';
function attClockTxt_(v){return String(v==null?'':v).trim();}
function attClockBool_(v,d){const s=attClockTxt_(v).toLowerCase();if(!s)return !!d;return ['نعم','yes','true','1','on'].indexOf(s)!==-1;}
function attClockSettings_(){const out={ATTENDANCE_SCHEDULE_START:'12:00',ATTENDANCE_LATE_GRACE_MINUTES:0,ATTENDANCE_ONE_CLOCKIN_PER_DAY:'نعم'};const sh=ss_().getSheetByName('إعدادات الدوام');if(!sh||sh.getLastRow()<2)return out;sh.getRange(2,1,sh.getLastRow()-1,4).getValues().forEach(r=>{const k=attClockTxt_(r[0]);if(k&&attClockBool_(r[3],true))out[k]=r[1];});return out;}
function attClockDateKey_(d){return Utilities.formatDate(d||new Date(),ATT_CLOCKIN_TZ_V1,'yyyy-MM-dd');}
function attClockTime_(d){return Utilities.formatDate(d||new Date(),ATT_CLOCKIN_TZ_V1,'HH:mm');}
function attClockSchedule_(){const cfg=attClockSettings_(),date=attClockDateKey_(),special=ss_().getSheetByName(ATT_CLOCKIN_SPECIAL_SHEET_V1);let start=attClockTxt_(cfg.ATTENDANCE_SCHEDULE_START||'12:00');if(special&&special.getLastRow()>1){const rows=special.getRange(2,1,special.getLastRow()-1,5).getValues();for(let i=rows.length-1;i>=0;i--){const r=rows[i],rd=r[0] instanceof Date?Utilities.formatDate(r[0],ATT_CLOCKIN_TZ_V1,'yyyy-MM-dd'):attClockTxt_(r[0]);if(rd===date&&attClockBool_(r[4],true)&&attClockTxt_(r[1])){start=attClockTxt_(r[1]);break;}}}return start;}
function attClockMinutes_(hhmm){const m=String(hhmm||'').match(/^(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):0;}
function attClockEnsureCols_(){const sh=ss_().getSheetByName('سجل الدوام');if(!sh)return null;if(sh.getMaxColumns()<20)sh.insertColumnsAfter(sh.getMaxColumns(),20-sh.getMaxColumns());sh.getRange(1,17,1,4).setValues([['موعد الحضور','تسجيل الحضور','فرق الدقائق','حالة الحضور']]);return sh;}
function attClockFindTodayRow_(username){const sh=attClockEnsureCols_();if(!sh||sh.getLastRow()<2)return null;const vals=sh.getRange(2,1,sh.getLastRow()-1,20).getValues(),today=attClockDateKey_();for(let i=vals.length-1;i>=0;i--){const r=vals[i],d=r[1] instanceof Date?attClockDateKey_(r[1]):attClockTxt_(r[1]).replace(/\//g,'-');if(attClockTxt_(r[2])===username&&(d===today||d===today.replace(/-/g,'/')))return {row:i+2,values:r,sheet:sh};}return null;}
function attendanceClockinV1_(e){e=e||{parameter:{}};const p=e.parameter||{},auth=authorize_(p.username,p.token);if(!auth.ok)return {success:false,message:auth.message};const username=attClockTxt_(auth.user.username||auth.user.name);let row=attClockFindTodayRow_(username);if(!row&&typeof attendanceStartV1_==='function'){attendanceStartV1_(auth);row=attClockFindTodayRow_(username);}if(!row)return {success:false,message:'تعذر إنشاء سجل الحضور؛ انشر Attendance backend أولًا.'};if(row.values[17]){return {success:true,alreadyRecorded:true,scheduledStart:attClockTxt_(row.values[16]),clockInAt:row.values[17],differenceMinutes:Number(row.values[18]||0),attendanceStatus:attClockTxt_(row.values[19])};}
const now=new Date(),scheduled=attClockSchedule_(),actual=attClockTime_(now),diff=attClockMinutes_(actual)-attClockMinutes_(scheduled),grace=Math.max(0,Number(attClockSettings_().ATTENDANCE_LATE_GRACE_MINUTES||0));let status='في الموعد';if(diff>grace)status='متأخر '+diff+' دقيقة';else if(diff<0)status='مبكر '+Math.abs(diff)+' دقيقة';row.sheet.getRange(row.row,17,1,4).setValues([[scheduled,now,diff,status]]);return {success:true,scheduledStart:scheduled,clockInAt:Utilities.formatDate(now,ATT_CLOCKIN_TZ_V1,"yyyy-MM-dd'T'HH:mm:ssXXX"),clockInTime:actual,differenceMinutes:diff,attendanceStatus:status};}
