// TrendOS HR V1 — employee self-service + admin HR records.
// High-impact employment decisions are never automated here.
const HR_REQ_SHEET_V1='HR - الطلبات والإجازات';
const HR_EMP_SHEET_V1='HR - الموظفين';
const HR_SKILL_SHEET_V1='HR - مصفوفة المهارات';
const HR_TZ_V1='Africa/Cairo';
function hrTxtV1_(v){return String(v==null?'':v).trim();}
function hrNormV1_(v){return hrTxtV1_(v).toLowerCase().replace(/[إأآا]/g,'ا').replace(/[ى]/g,'ي').replace(/[ةه]/g,'ه').replace(/\s+/g,' ').trim();}
function hrNowV1_(){return Utilities.formatDate(new Date(),HR_TZ_V1,"yyyy-MM-dd'T'HH:mm:ssXXX");}
function hrAuthV1_(p){const a=authorize_(p.username,p.token);if(!a.ok)return a;const role=hrTxtV1_(a.user.role).toLowerCase(),key=hrNormV1_((a.user.username||a.user.name||'')+' '+(a.user.role||''));a.isAdmin=role==='admin'||key.indexOf('ضياء')>=0||key.indexOf('diaa')>=0;a.employeeName=hrTxtV1_(a.user.name||a.user.username);return a;}
function hrRowsV1_(name){const sh=ss_().getSheetByName(name);if(!sh||sh.getLastRow()<2)return[];const d=sh.getDataRange().getValues(),h=d[0].map(hrTxtV1_);return d.slice(1).map((r,i)=>{const o={_row:i+2};h.forEach((x,j)=>o[x]=r[j]);return o;});}
function hrRequestListV1_(a){let rows=hrRowsV1_(HR_REQ_SHEET_V1);if(!a.isAdmin)rows=rows.filter(r=>hrNormV1_(r['الموظف'])===hrNormV1_(a.employeeName));return rows.reverse().slice(0,200).map(r=>({id:hrTxtV1_(r['رقم الطلب']),at:hrTxtV1_(r['تاريخ الطلب']),employee:hrTxtV1_(r['الموظف']),type:hrTxtV1_(r['نوع الطلب']),from:hrTxtV1_(r['من']),to:hrTxtV1_(r['إلى']),duration:hrTxtV1_(r['المدة']),reason:hrTxtV1_(r['سبب مختصر اختياري']),status:hrTxtV1_(r['الحالة']),decisionBy:hrTxtV1_(r['قرار بواسطة']),decisionNote:hrTxtV1_(r['ملاحظة القرار'])}));}
function hrSubmitV1_(a,p){const sh=ss_().getSheetByName(HR_REQ_SHEET_V1);if(!sh)return{success:false,message:'شيت HR غير موجود.'};const allowed=['إجازة','إذن','تغيير شيفت','تدريب','مستند/طلب إداري','أخرى'];const type=allowed.indexOf(hrTxtV1_(p.requestType))>=0?hrTxtV1_(p.requestType):'أخرى';const id='HR-'+Utilities.getUuid().slice(0,8).toUpperCase(),now=hrNowV1_();sh.appendRow([id,now,a.employeeName,type,hrTxtV1_(p.from),hrTxtV1_(p.to),hrTxtV1_(p.duration),hrTxtV1_(p.reason).slice(0,500),'قيد المراجعة','','','',now,hrTxtV1_(p.reference)]);return{success:true,id:id,message:'تم تسجيل طلبك للمراجعة.'};}
function hrDecisionV1_(a,p){if(!a.isAdmin)return{success:false,message:'الاعتماد للإدارة فقط.'};const status=hrTxtV1_(p.status),allowed=['مقبول','مرفوض','محتاج معلومات','ملغي'];if(allowed.indexOf(status)<0)return{success:false,message:'حالة غير صحيحة.'};const rows=hrRowsV1_(HR_REQ_SHEET_V1),r=rows.find(x=>hrTxtV1_(x['رقم الطلب'])===hrTxtV1_(p.requestId));if(!r)return{success:false,message:'الطلب غير موجود.'};const sh=ss_().getSheetByName(HR_REQ_SHEET_V1);sh.getRange(r._row,9,1,5).setValues([[status,a.employeeName,hrNowV1_(),hrTxtV1_(p.note).slice(0,500),hrNowV1_()]]);return{success:true};}
function hrEmployeeListV1_(a){if(!a.isAdmin)return[];return hrRowsV1_(HR_EMP_SHEET_V1).slice(0,500).map(r=>({id:hrTxtV1_(r['معرف الموظف']),name:hrTxtV1_(r['اسم الموظف']),department:hrTxtV1_(r['القسم']),title:hrTxtV1_(r['المسمى الوظيفي']),status:hrTxtV1_(r['حالة العمل']),relation:hrTxtV1_(r['نوع العلاقة']),compensation:hrTxtV1_(r['نظام المقابل']),primarySkill:hrTxtV1_(r['المهارة الأساسية']),backup:hrTxtV1_(r['البديل']),training:hrTxtV1_(r['حالة التدريب'])}));}
function hrSkillListV1_(a){if(!a.isAdmin)return[];return hrRowsV1_(HR_SKILL_SHEET_V1).slice(0,1000);}
function hrV1_(e){const p=(e&&e.parameter)||{},a=hrAuthV1_(p);if(!a.ok)return{success:false,message:a.message};const op=hrTxtV1_(p.op||'myRequests');if(op==='myRequests')return{success:true,requests:hrRequestListV1_(a)};if(op==='submitRequest')return hrSubmitV1_(a,p);if(op==='requests'&&a.isAdmin)return{success:true,requests:hrRequestListV1_(a)};if(op==='decide')return hrDecisionV1_(a,p);if(op==='employees'&&a.isAdmin)return{success:true,employees:hrEmployeeListV1_(a)};if(op==='skills'&&a.isAdmin)return{success:true,skills:hrSkillListV1_(a)};return{success:false,message:'عملية HR غير معروفة.'};}
