(function(){
'use strict';
if(window.__TRENDOS_HR_V1__)return;window.__TRENDOS_HR_V1__=true;if(window.MATBAGY_HR_V1===false)return;
const API=String(window.TREND_API_URL||window.API_URL||'').trim(),txt=v=>String(v==null?'':v).trim();
function state(){return window.trendosState||window.state||{};}function user(){return state().user||null;}function name(){const u=user()||{};return txt(u.username||u.name);}function isAdmin(){const u=user()||{},r=txt(u.role).toLowerCase(),n=name().toLowerCase();return r==='admin'||n==='ضياء'||n==='diaa';}
function auth(extra){const u=user()||{};return Object.assign({username:u.username||u.name||'',token:u.token||''},extra||{});}async function rawApi(action,extra){if(!API)throw new Error('API غير مضبوط');const q=new URLSearchParams(),p=auth(Object.assign({action},extra||{}));Object.keys(p).forEach(k=>q.set(k,txt(p[k])));const r=await fetch(API+(API.includes('?')?'&':'?')+q.toString(),{cache:'no-store',credentials:'omit'}),d=await r.json();if(!d||d.success===false)throw new Error((d&&d.message)||'backend unavailable');return d;}function hrApi(extra){return rawApi('hrV1',extra);}
function esc(v){return txt(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function style(){if(document.getElementById('trendHrV1Style'))return;const s=document.createElement('style');s.id='trendHrV1Style';s.textContent=`#trendHrBtn{position:fixed;left:14px;bottom:14px;z-index:2147483300;border:0;border-radius:999px;background:#111;color:#fff;padding:10px 14px;font-weight:800;box-shadow:0 8px 24px rgba(0,0,0,.2);cursor:pointer}#trendHrPanel{position:fixed;left:14px;bottom:62px;z-index:2147483301;width:min(390px,calc(100vw - 28px));max-height:70vh;overflow:auto;background:#fff;border:1px solid #dce5ed;border-radius:14px;box-shadow:0 16px 40px rgba(0,0,0,.2);padding:12px;direction:rtl;font-family:Tahoma,Arial;display:none}#trendHrPanel.open{display:block}#trendHrPanel h3{margin:0 0 10px}#trendHrPanel input,#trendHrPanel select,#trendHrPanel textarea{width:100%;box-sizing:border-box;margin:4px 0 8px;padding:8px;border:1px solid #cbd8e2;border-radius:9px;font-family:inherit}#trendHrPanel button{border:0;border-radius:9px;background:#005bff;color:#fff;padding:8px 10px;font-weight:800;cursor:pointer}#trendHrPanel .row{padding:8px 0;border-bottom:1px solid #edf1f4;font-size:12px;line-height:1.6}#trendHrPanel .muted{font-size:10px;color:#6b7b88}`;(document.head||document.documentElement).appendChild(s);}
async function fallbackRows(){const out=await rawApi('getMatbagyNotes',{}),me=name().toLowerCase();return (out.notes||[]).filter(n=>txt(n.category)==='HR_REQUEST'&&(isAdmin()||txt(n.title).toLowerCase().includes('|'+me+'|'))).slice(0,20).map(n=>{let p={};try{p=JSON.parse(txt(n.content)||'{}');}catch(e){}return{id:txt(n.title).split('|')[0],type:p.type||'طلب HR',status:'قيد المراجعة',from:p.from||'',to:p.to||'',reason:p.reason||''};});}
async function load(panel){let rows=[];try{const out=await hrApi({op:isAdmin()?'requests':'myRequests'});rows=out.requests||[];}catch(e){try{rows=await fallbackRows();}catch(_e){}}const box=panel.querySelector('[data-list]');box.innerHTML=rows.length?rows.slice(0,20).map(r=>`<div class="row"><b>${esc(r.type)} • ${esc(r.status)}</b><br>${esc(r.from||'')} ${r.to?'→ '+esc(r.to):''}<div class="muted">${esc(r.id||'')} ${r.reason?'• '+esc(r.reason):''}</div></div>`).join(''):'<div class="row">مفيش طلبات HR مسجلة.</div>';}
async function submit(panel){const type=panel.querySelector('[data-type]').value,from=panel.querySelector('[data-from]').value,to=panel.querySelector('[data-to]').value,duration=panel.querySelector('[data-duration]').value,reason=panel.querySelector('[data-reason]').value,status=panel.querySelector('[data-status]');status.textContent='جاري التسجيل...';let ok=false;try{const out=await hrApi({op:'submitRequest',requestType:type,from,to,duration,reason});ok=!!out.success;}catch(e){try{const id='HR-'+Date.now();await rawApi('saveMatbagyNote',{category:'HR_REQUEST',title:id+'|'+name()+'|'+new Date().toISOString(),content:JSON.stringify({type,from,to,duration,reason,employee:name(),status:'قيد المراجعة'})});ok=true;}catch(_e){}}status.textContent=ok?'تم تسجيل الطلب للمراجعة.':'تعذر تسجيل الطلب الآن.';if(ok){panel.querySelector('[data-reason]').value='';load(panel);}}
function build(){if(!API||!user()||!user().token)return;style();if(document.getElementById('trendHrBtn'))return;const b=document.createElement('button');b.id='trendHrBtn';b.textContent=isAdmin()?'👥 HR':'🧾 طلب HR';const p=document.createElement('section');p.id='trendHrPanel';p.innerHTML=`<h3>${isAdmin()?'👥 HR TrendOS':'🧾 طلب إداري / إجازة'}</h3><select data-type><option>إجازة</option><option>إذن</option><option>تغيير شيفت</option><option>تدريب</option><option>مستند/طلب إداري</option><option>أخرى</option></select><input data-from placeholder="من: تاريخ/وقت"><input data-to placeholder="إلى: تاريخ/وقت"><input data-duration placeholder="المدة"><textarea data-reason placeholder="سبب مختصر اختياري — بدون تفاصيل شخصية حساسة"></textarea><button data-submit>إرسال للمراجعة</button><div class="muted" data-status style="margin:8px 0"></div><h3 style="font-size:14px;margin-top:12px">آخر الطلبات</h3><div data-list>جاري التحميل...</div>`;document.body.appendChild(b);document.body.appendChild(p);b.onclick=()=>{p.classList.toggle('open');if(p.classList.contains('open'))load(p);};p.querySelector('[data-submit]').onclick=()=>submit(p);}
const t=setInterval(()=>{if(user()&&user().token){clearInterval(t);build();}},500);
})();
