// TrendOS Press Control V1 — fixed batch window, session timing and energy estimate.
const PRESS_SESSIONS_SHEET_V1 = 'تشغيل - جلسات المكبس';
const PRESS_SETTINGS_SHEET_V1 = 'تشغيل - إعدادات المكبس';
const PRESS_TZ_V1 = 'Africa/Cairo';
const PRESS_HEADERS_V1 = ['Session ID','التاريخ','المشغل','الداعم','موعد التشغيل الثابت','بداية فعلية','قفل فعلي','مدة التشغيل - دقيقة','Queue عند البداية','Queue عند القفل','عدد الأوردرات المكبوسة','دقيقة/أوردر','قدرة المكبس kW','استهلاك تقديري kWh','تعريفة الكهرباء جنيه/kWh','تكلفة كهرباء تقديرية','تكلفة كهرباء/أوردر','الحالة / ملاحظات'];
function pressTxt_(v){return String(v==null?'':v).trim();}
function pressNorm_(v){return pressTxt_(v).toLowerCase().replace(/[إأآا]/g,'ا').replace(/[ى]/g,'ي').replace(/[ةه]/g,'ه');}
function pressNow_(){return new Date();}
function pressDate_(){return Utilities.formatDate(pressNow_(),PRESS_TZ_V1,'yyyy-MM-dd');}
function pressNum_(v){const n=Number(v);return isFinite(n)?n:0;}
function pressEnsure_(){const ss=ss_();let sh=ss.getSheetByName(PRESS_SESSIONS_SHEET_V1);if(!sh)sh=ss.insertSheet(PRESS_SESSIONS_SHEET_V1);if(sh.getMaxColumns()<PRESS_HEADERS_V1.length)sh.insertColumnsAfter(sh.getMaxColumns(),PRESS_HEADERS_V1.length-sh.getMaxColumns());sh.getRange(1,1,1,PRESS_HEADERS_V1.length).setValues([PRESS_HEADERS_V1]);sh.setFrozenRows(1);return sh;}
function pressSettings_(){const out={PRESS_FIXED_START:'17:00',PRESS_START_GRACE_MINUTES:'15',PRESS_PRIMARY:'ريفان',PRESS_SUPPORT:'وائل',PRESS_BATCH_MODE:'نعم',PRESS_URGENT_OVERRIDE:'نعم',PRESS_POWER_KW:'',ELECTRICITY_RATE_EGP_KWH:'',PRESS_STRICT_MONITOR:'نعم'};const sh=ss_().getSheetByName(PRESS_SETTINGS_SHEET_V1);if(!sh||sh.getLastRow()<2)return out;sh.getRange(2,1,sh.getLastRow()-1,4).getValues().forEach(r=>{const k=pressTxt_(r[0]);if(k)out[k]=r[1];});return out;}
function pressAuth_(p){const a=authorize_(p.username,p.token);if(!a.ok)return a;const s=pressSettings_(), key=pressNorm_(pressTxt_(a.user.username||a.user.name)+' '+pressTxt_(a.user.role));const allowed=key.includes('ضياء')||key.includes('diaa')||key.includes(pressNorm_(s.PRESS_PRIMARY))||key.includes(pressNorm_(s.PRESS_SUPPORT))||pressNorm_(a.user.role)==='admin';return allowed?a:{ok:false,message:'تشغيل المكبس متاح لريفان ووائل والإدارة فقط.'};}
function pressHeaderMap_(headers){const m={};headers.forEach((h,i)=>m[pressTxt_(h)]=i);return m;}
function pressQueue_(){const sh=ss_().getSheetByName(typeof SHEET_NAME_ORDER_LINES!=='undefined'?SHEET_NAME_ORDER_LINES:'بنود الأوردرات')||ss_().getSheetByName('بنود الأوردرات');if(!sh||sh.getLastRow()<2)return {count:0,urgent:0,items:[]};const data=sh.getDataRange().getValues(),h=pressHeaderMap_(data[0]);const get=(r,keys)=>{for(const k of keys){if(h[k]!==undefined&&pressTxt_(r[h[k]]))return r[h[k]];}return '';};const done=['تم التسليم','جاهز للاستلام','ملغى','ملغي','مكرر'];const items=[];for(let i=1;i<data.length;i++){const r=data[i],dept=pressNorm_(get(r,['القسم'])),flag=pressNorm_(get(r,['مكبس حراري'])),st=pressTxt_(get(r,['الحالة']));if(done.includes(st))continue;if(!(dept.includes('مكبس')||flag==='نعم'||flag==='yes'||flag==='true'||flag==='1'))continue;items.push({orderId:pressTxt_(get(r,['رقم الأوردر','Order ID'])),customer:pressTxt_(get(r,['اسم الشات / المكتب','اسم العميل'])),status:st,priority:pressTxt_(get(r,['الأولوية']))});}return {count:items.length,urgent:items.filter(x=>pressNorm_(x.priority).includes('عاجل')||pressNorm_(x.priority)==='vip').length,items:items.slice(0,12)};}
function pressOpenSession_(){const sh=pressEnsure_();if(sh.getLastRow()<2)return null;const vals=sh.getRange(2,1,sh.getLastRow()-1,PRESS_HEADERS_V1.length).getValues();for(let i=vals.length-1;i>=0;i--){const r=vals[i];if(pressTxt_(r[17])==='شغال'&&!pressTxt_(r[6]))return {row:i+2,values:r};}return null;}
function pressSessionObj_(x){if(!x)return null;const r=x.values||x;return {sessionId:pressTxt_(r[0]),date:pressTxt_(r[1]),operator:pressTxt_(r[2]),support:pressTxt_(r[3]),fixedStart:pressTxt_(r[4]),startedAt:r[5]||'',endedAt:r[6]||'',durationMinutes:pressNum_(r[7]),queueStart:pressNum_(r[8]),queueEnd:pressNum_(r[9]),ordersPressed:pressNum_(r[10]),minutesPerOrder:r[11]||'',powerKw:r[12]||'',kwh:r[13]||'',rate:r[14]||'',cost:r[15]||'',costPerOrder:r[16]||'',status:pressTxt_(r[17])};}
function pressStatus_(){const s=pressSettings_(),q=pressQueue_(),open=pressOpenSession_();return {settings:s,queue:q,session:pressSessionObj_(open),costConfigReady:pressNum_(s.PRESS_POWER_KW)>0&&pressNum_(s.ELECTRICITY_RATE_EGP_KWH)>0};}
function pressStart_(auth){const existing=pressOpenSession_();if(existing)return {success:true,alreadyOpen:true,status:pressStatus_()};const s=pressSettings_(),q=pressQueue_(),sh=pressEnsure_(),id='PRESS-'+Utilities.getUuid(),who=pressTxt_(auth.user.username||auth.user.name);sh.appendRow([id,pressDate_(),who,pressTxt_(s.PRESS_SUPPORT),pressTxt_(s.PRESS_FIXED_START),pressNow_(),'','',q.count,'','','',pressNum_(s.PRESS_POWER_KW)||'', '',pressNum_(s.ELECTRICITY_RATE_EGP_KWH)||'','','','شغال']);return {success:true,status:pressStatus_()};}
function pressStop_(p,auth){const open=pressOpenSession_();if(!open)return {success:false,message:'لا توجد جلسة مكبس مفتوحة.'};const sh=pressEnsure_(),s=pressSettings_(),q=pressQueue_(),end=pressNow_(),start=new Date(open.values[5]),minutes=Math.max(1,Math.round((end-start)/60000)),done=Math.max(0,Math.round(pressNum_(p.ordersPressed))),power=pressNum_(s.PRESS_POWER_KW),rate=pressNum_(s.ELECTRICITY_RATE_EGP_KWH),kwh=power>0?Number((power*minutes/60).toFixed(3)):'',cost=(power>0&&rate>0)?Number((power*minutes/60*rate).toFixed(2)):'',mpo=done>0?Number((minutes/done).toFixed(2)):'',cpo=(done>0&&cost!=='')?Number((cost/done).toFixed(2)):'';sh.getRange(open.row,7,1,12).setValues([[end,minutes,open.values[8],q.count,done,mpo,power||'',kwh,rate||'',cost,cpo,cost===''?'مقفول — تكلفة الكهرباء تحتاج قدرة المكبس وتعريفة الكهرباء':'مقفول']]);return {success:true,status:pressStatus_()};}
function pressControlV1_(e){const p=(e&&e.parameter)||{},a=pressAuth_(p);if(!a.ok)return {success:false,message:a.message};const op=pressTxt_(p.op||'status');if(op==='status')return Object.assign({success:true},pressStatus_());if(op==='start')return pressStart_(a);if(op==='stop')return pressStop_(p,a);return {success:false,message:'عملية مكبس غير معروفة.'};}
