import assert from 'node:assert/strict';
import fs from 'node:fs';
const y=fs.readFileSync('.github/workflows/easystore-a2-bounded-canary-control.yml','utf8');
assert.ok(y.includes("options: [CHECK, ARM, DISABLE]"));
assert.ok(y.includes("ARM_ONE_EASYSTORE_CANARY"));
assert.ok(y.includes("action!=='saveAccountingTemplate'"));
assert.ok(y.includes("mode='CANARY'"));
assert.ok(y.includes("mode='READONLY'"));
assert.ok(y.includes("max_amount=0"));
assert.ok(y.includes("max_commands=1"));
assert.ok(y.includes("commands_started=0"));
assert.ok(y.includes("allowed_usernames_json='[]'"));
assert.ok(y.includes("allowed_actions_json='[]'"));
assert.ok(y.indexOf("SET mode='READONLY'") < y.indexOf("allowed_usernames_json='[]'"), 'disable must close authority before clearing allowlists');
assert.ok(y.includes("GENERAL transition forbidden"));
assert.ok(!/SET mode='GENERAL'/.test(y));
assert.ok(y.includes("A2_CANARY_CONTROL_BUSINESS_MUTATION=NO"));
console.log('A2_BOUNDED_CANARY_CONTROL_WORKFLOW=PASS');
console.log('FIRST_ACTION_LOCK=saveAccountingTemplate');
console.log('FIRST_CANARY_COMMAND_BUDGET=1');
console.log('GENERAL_TRANSITION=FORBIDDEN');
console.log('DISABLE_ORDER=READONLY_THEN_EMPTY_ALLOWLISTS');
console.log('PRODUCTION_MUTATION=NO');
