import assert from 'node:assert/strict';
import {CATEGORIES,reconcileOpening} from '../scripts/easystore_acc166_opening_reconcile.mjs';
const source=CATEGORIES.map((category,i)=>({category,id:'SYNTHETIC-ENTITY-'+i,sourceRef:'SYNTHETIC-EVIDENCE',amount:i===0?12.25:0}));
const manifest={cutoverDate:'2026-10-10',authorityRef:'SYNTHETIC-FIXTURE-ONLY',targetSnapshotRef:'SYNTHETIC-TARGET-ONLY',ownerApproved:true};
const fixture={manifest,source,target:source.map(x=>({...x}))};
assert.equal(reconcileOpening({...fixture,manifest:{...manifest,ownerApproved:false}}).decision,'NO_GO');
assert.equal(reconcileOpening({...fixture,manifest:{...manifest,authorityRef:''}}).decision,'NO_GO');
assert.equal(reconcileOpening({...fixture,source:[],target:[]}).decision,'NO_GO');
const passed=reconcileOpening(fixture);
assert.equal(passed.decision,'RECONCILED_OFFLINE_ONLY');
assert.equal(passed.entitiesCompared,CATEGORIES.length);
assert.equal(passed.financialLaunchAuthorized,false);
const mismatched=structuredClone(fixture);
mismatched.target[0].amount=13.25;
assert.equal(reconcileOpening(mismatched).unmatched,1);
assert.equal(reconcileOpening(mismatched).decision,'NO_GO');
const missing=structuredClone(fixture); missing.target.pop();
assert.equal(reconcileOpening(missing).decision,'NO_GO');
assert.equal(reconcileOpening(missing).unmatched,1);
const dup=structuredClone(fixture);dup.target.push({...dup.target[0]});
assert.throws(()=>reconcileOpening(dup),/duplicate/);
console.log('ACC166_OPENING_EXACT_ENTITY_RECONCILIATION_SYNTHETIC=PASS');
console.log('ACC166_OPENING_OWNER_APPROVAL_MISSING_FAIL_CLOSED=PASS');
console.log('ACC166_OPENING_REAL_FINANCE_DATA=NOT_VERIFIED');
