const fs=require('fs'),assert=require('assert');
const root=process.argv[2]||process.cwd();
const pkg=JSON.parse(fs.readFileSync(root+'/trendos-integrity-v1.package.json','utf8'));
assert.strictEqual(pkg.status,'PREPARED_NOT_APPROVED_FOR_PRODUCTION');
assert.strictEqual(pkg.featureFlag.name,'TRENDOS_INTEGRITY_V1_ENABLED');
assert.strictEqual(pkg.featureFlag.default,false);
assert.ok(Array.isArray(pkg.coreAppsScriptFiles)&&pkg.coreAppsScriptFiles.length>=10);
assert.ok(Array.isArray(pkg.optionalPerformanceFiles));assert.ok(Array.isArray(pkg.frontendFiles));assert.ok(Array.isArray(pkg.forbiddenFiles));
const all=[...pkg.coreAppsScriptFiles,...pkg.optionalPerformanceFiles,...pkg.frontendFiles];
all.forEach(f=>assert.ok(fs.existsSync(root+'/'+f),'package file missing: '+f));
pkg.forbiddenFiles.forEach(f=>assert.ok(!pkg.coreAppsScriptFiles.includes(f),'forbidden core file: '+f));
assert.ok(!pkg.coreAppsScriptFiles.includes('Code.gs'));
assert.ok(!pkg.coreAppsScriptFiles.includes('D1_Fast_Auth_V2_5_Safe.gs'),'Fast Auth must stay optional for first Core activation');
assert.deepStrictEqual(pkg.optionalPerformanceFiles,['D1_Fast_Auth_V2_5_Safe.gs']);
const router=fs.readFileSync(root+'/trendos-integrity-router-v1.gs','utf8');
assert.ok(router.includes("TRENDOS_INTEGRITY_ENABLED_PROP_V1='TRENDOS_INTEGRITY_V1_ENABLED'"));
assert.ok(router.includes('if(!trendosIntegrityEnabledV1_())return null;'));
assert.ok(router.includes("if(!trendosIntegrityEnabledV1_()||!payload"));
const coreSrc=pkg.coreAppsScriptFiles.map(f=>fs.readFileSync(root+'/'+f,'utf8')).join('\n');
assert.ok(!coreSrc.includes('D1_FAST_AUTH_V24'),'V2.4 must not be referenced by Core package');
assert.ok(!coreSrc.includes('authorizeD1FastV24_'),'V2.4 auth must not be referenced by Core package');
assert.ok(!/sk-[A-Za-z0-9_-]{20,}/.test(coreSrc));assert.ok(!/EAA[A-Za-z0-9]{30,}/.test(coreSrc));
const v25=fs.readFileSync(root+'/D1_Fast_Auth_V2_5_Safe.gs','utf8');
assert.ok(v25.includes('trendosFastAuthSafeUserV25_'));assert.ok(v25.includes('TRENDOS_FAST_AUTH_V25_REV_PREFIX'));
assert.ok(!/"password"\s*:\s*trendosFastAuthTextV25_/.test(v25));assert.ok(!/"token"\s*:\s*trendosFastAuthTextV25_/.test(v25));
console.log('TrendOS Pre-deploy package V1 safety gate: OK');