const fs=require('fs'),vm=require('vm'),crypto=require('crypto'),assert=require('assert');
const root=process.argv[2]||process.cwd();
const foundation=fs.readFileSync(root+'/trendos-integrity-v1.gs','utf8');
const moduleSrc=fs.readFileSync(root+'/trendos-handover-ops-integrity-v1.gs','utf8');
class FakeRange{constructor(sh,r,c,nr=1,nc=1){Object.assign(this,{sh,r,c,nr,nc});}getValues(){const out=[];for(let i=0;i<this.nr;i++){const row=[];for(let j=0;j<this.nc;j++)row.push(this.sh.cell(this.r+i,this.c+j));out.push(row);}return out;}setValues(v){for(let i=0;i<this.nr;i++)for(let j=0;j<this.nc;j++)this.sh.set(this.r+i,this.c+j,v[i][j]);return this;}getValue(){return this.sh.cell(this.r,this.c);}setValue(v){this.sh.set(this.r,this.c,v);return this;}}
class FakeSheet{constructor(name){this.name=name;this.rows=[];this.maxColumns=1;}getName(){return this.name;}getLastRow(){return this.rows.length;}getLastColumn(){return Math.max(1,this.maxColumns,...this.rows.map(r=>r.length));}getMaxColumns(){return this.maxColumns;}insertColumnsAfter(_a,count){this.maxColumns+=count;}getRange(r,c,nr=1,nc=1){return new FakeRange(this,r,c,nr,nc);}appendRow(row){this.maxColumns=Math.max(this.maxColumns,row.length);this.rows.push(row.slice());}setFrozenRows(){}cell(r,c){return this.rows[r-1]&&this.rows[r-1][c-1]!==undefined?this.rows[r-1][c-1]:'';}set(r,c,v){while(this.rows.length<r)this.rows.push([]);while(this.rows[r-1].length<c)this.rows[r-1].push('');this.rows[r-1][c-1]=v;this.maxColumns=Math.max(this.maxColumns,c);}}
class FakeSpreadsheet{constructor(){this.sheets={};}getSheetByName(n){return this.sheets[n]||null;}insertSheet(n){if(this.sheets[n])throw new Error('exists');return this.sheets[n]=new FakeSheet(n);}}
const fakeSs=new FakeSpreadsheet();
const legacyHeaders=['ID','التاريخ/الوقت','الموظف','القسم','رقم الأوردر/المهمة','الحالة الحقيقية','سبب التوقف','الخطوة التالية','يسلم إلى','حالة الاستلام','ملاحظة المدير','آخر تحديث'];
const legacy=fakeSs.insertSheet('إدارة - تسليم الشيفت');legacy.appendRow(legacyHeaders);
let uuidCounter=0;
const ctx={console,Date,JSON,Object,Array,String,Number,Math,RegExp,isFinite,isNaN,Utilities:{DigestAlgorithm:{SHA_256:'SHA_256'},Charset:{UTF_8:'UTF_8'},computeDigest(_a,v){return Array.from(crypto.createHash('sha256').update(String(v),'utf8').digest()).map(x=>x>127?x-256:x);},formatDate(d,tz,fmt){assert.strictEqual(tz,'Africa/Cairo');if(fmt==='yyyy-MM-dd')return new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).format(d);if(fmt==='HH')return new Intl.DateTimeFormat('en-GB',{timeZone:tz,hour:'2-digit',hour12:false}).format(d);throw new Error('fmt '+fmt);},getUuid(){uuidCounter++;return ('0000000'+uuidCounter).slice(-8)+'-1111-2222-3333-444444444444';}},LockService:{getScriptLock(){return{waitLock(){},releaseLock(){}}},getUserLock(){return{waitLock(){},releaseLock(){}}},getDocumentLock(){return{waitLock(){},releaseLock(){}}}},ss_:()=>fakeSs};
vm.createContext(ctx);vm.runInContext(foundation,ctx,{filename:'trendos-integrity-v1.gs'});vm.runInContext(moduleSrc,ctx,{filename:'trendos-handover-ops-integrity-v1.gs'});
const self=ctx.trendosHandoverOpsSelfTestV1_();assert.strictEqual(self.success,true,JSON.stringify(self.checks.filter(x=>!x.pass)));
const lineLookup=id=>({lineId:id,orderId:'3637',department:'طباعة',status:'تحت التنفيذ',assignedTo:'وائل'});
const base={employee:'وائل',department:'طباعة',orderId:'3637',lineId:'3637-02',businessDate:'2026-08-30',shift:'DAY',status:'تحت التنفيذ',blocker:'',nextAction:'استكمال الطباعة',nextOwner:'ريفان'};
const h1=ctx.trendosCreateHandoverV1_(base,{lineLookup});assert.strictEqual(h1.success,true);assert.strictEqual(h1.duplicate,false);
const h2=ctx.trendosCreateHandoverV1_(base,{lineLookup});assert.strictEqual(h2.duplicate,true);assert.strictEqual(h2.id,h1.id);
const h3=ctx.trendosCreateHandoverV1_(Object.assign({},base,{nextAction:'تسليم للمكبس'}),{lineLookup});assert.strictEqual(h3.duplicate,false);assert.notStrictEqual(h3.id,h1.id);
assert.throws(()=>ctx.trendosCreateHandoverV1_(Object.assign({},base,{orderId:'9999'}),{lineLookup}),/لا يطابق/);
assert.throws(()=>ctx.trendosCreateHandoverV1_(base,{lineLookup:id=>({lineId:id,orderId:'3637',department:'طباعة',status:'تم التسليم'})}),/ليس سطر تشغيل مفتوح/);
const evolved=fakeSs.getSheetByName('إدارة - تسليم الشيفت').rows[0];assert.deepStrictEqual(Array.from(evolved.slice(0,legacyHeaders.length)),legacyHeaders);['Line ID','تاريخ العمل','الشيفت','State Fingerprint','مفتاح الحدث','Revision','استلم بواسطة','وقت الاستلام'].forEach(h=>assert.ok(evolved.includes(h),h));
assert.throws(()=>ctx.trendosReceiveHandoverV1_({id:h3.id,receiver:'شخص آخر'}),/لا يطابق/);const r1=ctx.trendosReceiveHandoverV1_({id:h3.id,receiver:'ريفان'});assert.strictEqual(r1.duplicate,false);const r2=ctx.trendosReceiveHandoverV1_({id:h3.id,receiver:'ريفان'});assert.strictEqual(r2.duplicate,true);assert.throws(()=>ctx.trendosReceiveHandoverV1_({id:h3.id,receiver:'وائل'}),/موظف آخر/);
const rep1=ctx.trendosSaveOpsReplyV1_({requestId:'req-1',employee:'وائل',department:'طباعة',lineId:'3637-02',content:'الشغل واقف انتظار العميل',businessDate:'2026-08-30'},{lineLookup});const rep2=ctx.trendosSaveOpsReplyV1_({requestId:'req-1',employee:'وائل',department:'طباعة',lineId:'3637-02',content:'نص مختلف لنفس retry',businessDate:'2026-08-30'},{lineLookup});assert.strictEqual(rep2.duplicate,true);assert.strictEqual(rep2.eventId,rep1.eventId);const fup1=ctx.trendosOpsMarkReplyFollowedUpV1_({eventId:rep1.eventId,coachNoteId:'COACH-X'});assert.strictEqual(fup1.duplicate,false);const fup2=ctx.trendosOpsMarkReplyFollowedUpV1_({eventId:rep1.eventId,coachNoteId:'COACH-X'});assert.strictEqual(fup2.duplicate,true);
const coachBase={employee:'وائل',department:'طباعة',lineId:'3637-02',businessDate:'2026-08-30',status:'تحت التنفيذ',nextAction:'استكمال',message:'راجع الأوردر 3637'};const c1=ctx.trendosCreateOpsCoachV1_(coachBase,{lineLookup});const c2=ctx.trendosCreateOpsCoachV1_(coachBase,{lineLookup});assert.strictEqual(c2.duplicate,true);assert.strictEqual(c2.eventId,c1.eventId);const c3=ctx.trendosCreateOpsCoachV1_(Object.assign({},coachBase,{status:'متوقف',blocker:'انتظار العميل',message:'تابع العميل'}),{lineLookup});assert.strictEqual(c3.duplicate,false);assert.notStrictEqual(c3.eventId,c1.eventId);
let runs=0;const now=new Date('2026-08-30T14:10:00Z');const a1=ctx.trendosRunTrendMasterAutomationSafeV1_({now,runner:()=>{runs++;return{success:true,queued:3};}});assert.strictEqual(a1.success,true);assert.strictEqual(runs,1);const a2=ctx.trendosRunTrendMasterAutomationSafeV1_({now,runner:()=>{runs++;return{success:true,queued:9};}});assert.strictEqual(a2.duplicate,true);assert.strictEqual(runs,1);assert.strictEqual(a2.result.queued,3);const failNow=new Date('2026-08-30T15:10:00Z');assert.throws(()=>ctx.trendosRunTrendMasterAutomationSafeV1_({now:failNow,runner:()=>{runs++;throw new Error('boom')}}),/boom/);const blocked=ctx.trendosRunTrendMasterAutomationSafeV1_({now:failNow,runner:()=>{runs++;return{success:true,queued:1};}});assert.strictEqual(blocked.success,false);assert.strictEqual(blocked.failed,true);const retry=ctx.trendosRunTrendMasterAutomationSafeV1_({now:failNow,retryFailed:true,runner:()=>{runs++;return{success:true,queued:1};}});assert.strictEqual(retry.success,true);assert.strictEqual(retry.duplicate,false);
assert.ok(!/sk-[A-Za-z0-9_-]{20,}/.test(moduleSrc));assert.ok(!/EAA[A-Za-z0-9]{30,}/.test(moduleSrc));console.log('TrendOS Handover / OPS integrity V1 tests: OK');
